version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip"
      - "unzip terraform_0.12.20_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve
